version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - poc_springboot:/var/lib/mysql
      
volumes:
  poc_springboot: